apiVersion: v2
name: kubebridge
description: A Service Discovery for Kubernetes
icon: https://raw.githubusercontent.com/hayk96/kubebridge/4ff0630fbd34d794211567cb1d07ddb0d35b8af2/docs/images/logo.svg
maintainers:
  - name: Hayk Davtyan
    url: https://github.com/hayk96
keywords:
  - service-discovery
  - networking
  - kubernetes
  - dns

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.2.1

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "v0.2.1"

dependencies:
  - name: redis
    repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
    version: 20.11.3
    condition: redis.enabled
