{{- if .Values.sync.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubebridge-sync-role-binding
subjects:
- kind: ServiceAccount
  name: kubebridge-sync-sa
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: kubebridge-sync-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}