apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubebridge.fullname" . }}-dns
  labels:
    {{- include "kubebridge.labels" . | nindent 4 }}
    app.kubernetes.io/component: dns
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.sync.service.type }}
  ports:
    - name: tcp
      protocol: TCP
      port: 53
      targetPort: 53
    - name: udp
      protocol: UDP
      port: 53
      targetPort: 53
  selector:
    {{- include "kubebridge.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: dns
