{{- if and .Values.redis.auth.enabled .Values.redis.auth.generatePassword -}}
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
type: Opaque
data:
  redis-username: {{ "default" | b64enc }}
  redis-password: {{- $existing := (lookup "v1" "Secret" .Release.Namespace "redis-secret") -}}
            {{- if $existing }}
              {{ index $existing.data "redis-password" }}
            {{- else }}
              {{ randAlphaNum 16 | b64enc }}
            {{- end }}
{{- end }}