{{- if .Values.sync.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubebridge-sync-sa
  labels:
    {{- include "kubebridge.labels" . | nindent 4 }}
    app.kubernetes.io/component: sync
  {{- with .Values.sync.serviceAccount.annotations }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
