name: Release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+-*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v4.1.0
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Export GPG key to legacy format
        run: gpg --export-secret-keys > ~/.gnupg/pubring.gpg

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.7.2

      - name: Add dependency chart repos
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami        

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        with:
          config: cr.yaml
          charts_dir: charts
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_SKIP_EXISTING: "true"
