name: Release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+-*

env:
  SHA: ${{ github.sha }}

jobs:
  pre:
    name: .pre
    permissions:
      contents: write
    uses: ./.github/workflows/build.yml
    secrets: inherit

  push:
    name: Push Docker images
    runs-on: ubuntu-24.04
    needs: [pre]
    permissions:
      packages: write
      contents: read
      actions: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare job outputs
        id: op
        run: |
          echo "tag=${GITHUB_REF#refs/*/}" >> "$GITHUB_OUTPUT"
          echo "date=$(date +%Y-%m-%d)"    >> "$GITHUB_OUTPUT"
          echo "app_version=$(sed "s/^v//" <<< ${GITHUB_REF#refs/*/})" >> "$GITHUB_OUTPUT"
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-${{ env.SHA }}
          path: /tmp
      - name: Load image
        run: |
          docker load --input /tmp/${{ github.event.repository.name }}-${{ github.sha }}.tar
          docker tag ${{ github.repository }}:${{ github.sha }} ${{ github.repository }}:${{ steps.op.outputs.tag }}
          docker tag ${{ github.repository }}:${{ github.sha }} ghcr.io/${{ github.repository }}:${{ steps.op.outputs.tag }}
      - name: Login to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Login to the GH Container registry
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push Docker images to DockerHub
        run: |
          docker push docker.io/${{ github.repository }}:${{ steps.op.outputs.tag }}
          docker push docker.io/${{ github.repository }}:latest
      - name: Push Docker images to GH Container registry
        run: |
          docker push ghcr.io/${{ github.repository }}:${{ steps.op.outputs.tag }}
          docker push ghcr.io/${{ github.repository }}:latest
    outputs:
       gitTag: ${{ steps.op.outputs.tag }}
       appVersion: ${{ steps.op.outputs.app_version }}
       date: ${{ steps.op.outputs.date }}

#  update-changelog:
#    name: Update Changelog
#    runs-on: ubuntu-24.04
#    needs: [push]
#    permissions:
#      contents: write
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#        with:
#          fetch-depth: 0
#      - name: Get previous tag
#        id: previousTag
#        run: |
#          name=$(git --no-pager tag --sort=creatordate --merged ${{ github.ref_name }} | tail -2 | head -1)
#          echo "previousTag: $name"
#          echo "previousTag=$name" >> $GITHUB_ENV
#      - name: Update CHANGELOG
#        id: changelog
#        uses: requarks/changelog-action@v1
#        with:
#          token: ${{ secrets.GITHUB_TOKEN }}
#          fromTag: ${{ github.ref_name }}
#          toTag: ${{ env.previousTag }}
#          writeToFile: true
#          useGitmojis: false
#          includeInvalidCommits: true
#      - name: Import GPG key
#        uses: crazy-max/ghaction-import-gpg@v5
#        with:
#          gpg_private_key: ${{ secrets.GH_ACTIONS_BOT_GPG_PRIVATE_KEY }}
#          passphrase: ${{ secrets.GH_ACTIONS_BOT_GPG_PASSPHRASE }}
#          git_user_signingkey: true
#          git_commit_gpgsign: true
#      - name: Commit CHANGELOG.md
#        uses: stefanzweifel/git-auto-commit-action@v5
#        with:
#          branch: main
#          commit_options: '-s -S'
#          commit_user_name: github-actions[bot]
#          commit_user_email: 46712946+hayk96@users.noreply.github.com
#          commit_author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
#          commit_message: 'docs: update CHANGELOG.md for ${{ github.ref_name }}'
#          file_pattern: CHANGELOG.md

  publish-chart:
    name: Publish Helm chart
    runs-on: ubuntu-24.04
    needs: [push]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Fetch latest tag
        id: latest_tag
        run: |
          git fetch --tags
          latest=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "Latest tag: $latest"
          git checkout $latest
          echo "tag=$latest" >> $GITHUB_OUTPUT
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v4.1.0
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
      - name: Export GPG key to legacy format
        run: gpg --export-secret-keys > ~/.gnupg/pubring.gpg
      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.7.2
      - name: Add dependency chart repos
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        with:
          config: cr.yaml
          charts_dir: charts
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_SKIP_EXISTING: "true"
